### ISSUE TITLE
"[Bug]" clockskew

### ISSUE THREAD

**Issue by deralexxx** [LDO-CERT/mans_to_es#5]
Within mans files. there is a value in the **manifest.json** called _skew_.
In metadata.json the value is called: "**clockSkew**" Not sure where the difference is.

This is meant to be the offset of the system clock.

That value can be pretty high and if not respected, the resulting timeline if off by that value.

Some example values:
`
-pt64s --> ofset: -01:04 min

+PT16710S --> offset +4 h38:30
`
So the number is seconds and the + or - is a prefix to tell how to interpret the offset.

imho mans_to_es should respect or at least tell if there is such an offset to calculate the normalized timeline afterwards.

Thx

**Comment by garanews** [comment]
added support in release 1.4 https://github.com/LDO-CERT/mans_to_es/commit/38329e2eef0a1be3504df5c1cd3312158be3af5e
