### ISSUE TITLE
"[Bug]" If hits.json does not exist parsing will stop

### ISSUE THREAD

**Issue by inn3rself** [LDO-CERT/mans_to_es#6]
When trying to parse a .mans file got from a host that did not trigger an alert the hits.json file will not exist and mans_to_es will exit.

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mans_to_es/mans_to_es.py", line 570, in main
    mte.get_hits()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mans_to_es/mans_to_es.py", line 303, in get_hits
    with open(os.path.join(self.folder_path, "hits.json"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxxxxxxxx.mans__tmp/hits.json'

Cheers

**Comment by garanews** [comment]
This is related to #1 and is already managed in refactoring_test branch, but we're still working to port it on master branch.
You can test it but at the moment is not performing so well due to big xml files contained in "Comprehensive Investigative Details" .mans

**Comment by garanews** [comment]
fixed  in release 1.4 https://github.com/LDO-CERT/mans_to_es/commit/38329e2eef0a1be3504df5c1cd3312158be3af5e
